-- È¸¿ø
CREATE TABLE MEMBER (
   ID VARCHAR2(40) NOT NULL, 
   PW VARCHAR2(20), 
   MEMBER_NAME VARCHAR2(20), 
   COUPLE_NO NUMBER
);

ALTER TABLE MEMBER
   ADD
      CONSTRAINT PK_MEMBER
      PRIMARY KEY (
         ID
      );
